baseURL = "https://peekaboo.travel"
languageCode = "en-us"
title = "Peekaboo World"
theme = "casper-two"
publishDir = "docs"
paginate="5000"


[params]
  title       = "Peekaboo World"
  subtitle    = ""

  cover       = "img/home-bg.jpg"
  description = "Here to inspire global curiosity and learning through travel.."
  metaDescription = "Here to inspire global curiosity and learning through travel."
  googleAnalytics = "UA-133850075-1"
  customCSS =  ["css/site.css"]

  fbName = "Peekaboo-400441367190219"
  instagramName = "peekabootravel"

  logo = "img/travel-icon-22.png"
  orgName = "Andrea"
  orgWebsite = "https://peekaboo.travel/about/"
  orgDescription = "Here to inspire global curiosity and learning through travel."

  author = "Andrea"
  authorAvatar = "img/a.jpg"
  authorLocation = "Budapest, HU"
  authorWebsite = "https://peekaboo.travel/about/"
  authorDescription = "Mom to two littles"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "caspertwo"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 100

[author]
  name = "Andrea"