baseURL = "https://peekaboo.travel"
languageCode = "en-us"
title = "Peekaboo World"
theme = "startbootstrap-clean-blog"
publishDir = "docs"
googleAnalytics = "UA-133850075-1"

[author]
  name = "Andrea"

[params]
  DateForm = "Thu, Feb 7, 2018"
  # Description = "Travel the world with kiddos"
  Description = "Stay Tuned ..."
  Author = "Andrea"
  # email = "anew09@gmail.com"
  postSummariesFrontPage = 2
  showReadTime = true

[[params.social]]
    title = "instagram"
    url = "https://www.instagram.com/peekabootravel"
[[params.social]]
    title = "twitter"
    url = "https://twitter.com/peekabo78100593"
[[params.social]]
    title = "facebook"
    url = "https://www.facebook.com/Peekaboo-400441367190219"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200